services:
  # The API Server Service
  server:
    build:
      context: ./server
    ports:
      - "5175:5175"
    volumes:
      - ./server/db.sqlite:/usr/src/app/db.sqlite
    environment:
      - NODE_ENV=production
      - PORT=5175

  # The React Client Service
  client:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
