name: wex-automotive   # Project name for containers, networks, volumes

services:
  # The API Server Service
  server:
    build:
      context: ./server
    image: wex-automotive/server:latest   # Explicit image name
    ports:
      - "5175:5175"
    volumes:
      - ./server/db.sqlite:/usr/src/app/db.sqlite
    environment:
      - NODE_ENV=production
      - PORT=5175

  # The React Client Service
  client:
    build:
      context: ./client
    image: wex-automotive/client:latest   # Explicit image name
    ports:
      - "5173:80"
    depends_on:
      - server
